### PR TITLE
Add chipDescriptionPath

### PR DESCRIPTION
**Pull request by bugadani**
I'm guessing this needs https://github.com/probe-rs/probe-rs/pull/2050 and it's also untested

### CODE REVIEW

**Review by noppej — DISMISSED** [review]
As you've hinted at, I'm using this "request changes" to block this merge until we have merged and released https://github.com/probe-rs/probe-rs/pull/2050 :)

**Comment by Yatekii** [comment]
This needs resolving :)

**Comment by bugadani** [comment]
First probe-rs needs a new release :P I'll wait for resolving this in case we end up breaking it again

**Comment by noppej** [comment]
> This needs resolving :)

@Noah ... I'm not sure I fully understand what you mean by "needs resolving". Do you have a request beyond the comment I made at https://github.com/probe-rs/vscode/pull/71#pullrequestreview-1821856091 ?

**Comment by Yatekii** [comment]
@noppej sorry I only see the comment now: I meant the merge conflicts :)

**Review by Yatekii — APPROVED** [review]

**Pull request merged**
