### PR TITLE
Add development instructions to README, fix some typos

### PR DESCRIPTION
**Pull request by Tiwalun**

### CODE REVIEW

**Comment by noppej** [comment]
@Tiwalun ...Thanks for the typos. I notice many of the file changes are 'style' related (include { on same line versus new line, etc.).  Was this on purpose?

Also, the https://probe.rs/docs/tools/vscode/ page already has instructions for development. Your additions there would be helpful. Can we standardize on place for these, so that we don't  introduce inconsistency over time?

**Comment by Tiwalun** [comment]
I think the style changes got applied by VS Code automatically, probably because I've enabled format on save?
I can also undo these changes, if you don't like them. Personally, I prefer to use code formatters whenever possible, so we could also enforce the use of a code formatter, similar to the Rust repos?

I personally prefer to have at least some documentation in the README, so I can get started directly after cloning the repository. I also think it reduces the friction to update the instructions, since it can be done at the same time as changing the code. For extensive documentation, the website is probably a better place.

**Comment by noppej** [comment]
I agree with declaring some consistent style/formatting. If you have a preference, I suggest we add it into `extensions.json` and `settings.json` so that it makes it easy for all contributors to comply. 

On the point of docs, that also makes sense. Why don't we agree to keep user documentation in the probe-rs website guide, and then the development instructions in the `README` for the repo? If you are aligned, can you please merge appropriately and update the guide?

**Comment by Tiwalun** [comment]
I've added the remaining development instructions from the website, and will create a separate PR to remove them from the website after this is merged.

I'm not sure what typescript code formatter is commonly used, so I'm not sure what would be the best one to use. Do you have an idea?

**Comment by noppej** [comment]
I don't ... but if you just use what you used, and then add 'settings.json' for the format on save, then at least we have consistency.  If anyone wants to add TypeScript expertise later, we can PR that separately.  What do you think?

**Comment by Yatekii** [comment]
I think `prettier` is pretty much what is used commonly.

**Review by Yatekii — APPROVED** [review]
Thanks :)

bors r+

**Pull request merged**
