### PR TITLE
Update or remove(if appropriate) incorrect defaults.

### LINKED ISSUE #75: Display the flashing progress in some form
Maybe I'm just missing where it should be, but as far as I can tell, there is currently no way for the user to see the current status of the flashing progress.

### PR DESCRIPTION
**Pull request by bugadani**
Closes #75 because the root cause of it was an incorrect assumption made from incorrect defaults.

### CODE REVIEW

**Review by noppej — CHANGES_REQUESTED** [review]
@bugadani Is this a work in progress? I cannot see where in the currently committed code the defaults have been changed.

Also, I wonder if removing the defaults might do more harm than good? Would it not be a better user experience to harmonize the defaults with the `probe-rs` implementation. That way, `launch.json` will hint at the correct default.

Finally, if we change the schema, it would be really nice if we can cleanup the appropriate references in [the docs](https://probe.rs/docs/tools/debugger/). If that is too much to ask, please open an issue against https://github.com/probe-rs/webpage, and I'd be happy to add it to my list.

**Comment by Yatekii** [comment]
He just synchronized the VSCode config schema with the actual default values we use :)

**Comment by noppej** [comment]
Github is so strange. I looked at the changes just before typing that comment, and there were no changes to the default in `package.json` ... just the dependency updates.

I looked again, and they are all there.

**Comment by noppej** [comment]
The code changes looks fine, and I'm happy to approve. However, if we release this PR, the docs will contradict the product.

**Comment by Yatekii** [comment]
Tbh, this is the docs. If you configure stuff you look at the autocompletion of vscode :)

**Comment by noppej** [comment]
I'd be OK if we decide to rip relevant pieces where contradictions exist, from the docs? It makes more sense now that intellisense actually works (courtesy of @bugadani efforts ☺️)

**Comment by bugadani** [comment]
For some cases the defaults made no sense to me. For example, the SVD path - if it's not set, probe-rs just doesn't use it instead of defaulting to whatever the extension specified. Program binary is required, so a default again makes little sense to me. Forgot to sack npx, sorry about that

**Review by noppej — APPROVED** [review]
Thanks @bugadani ... having "working" intellisense, that gives the "correct" guidance is valuable for usability.

**Pull request merged**
