### PR TITLE
Revert "Start using prettier"

### PR DESCRIPTION
**Pull request by Yatekii**
Reverts probe-rs/vscode#32

@dbrgn ... bringing forward my requests from #32:
- Please can we ensure we do not reformat `src/debugProtocol.json` ... this file is downloaded from the DAP spec in one of the npm scripts.
- I really appreciate the work you've done here, but I'd prefer if we can hold of a few days with merging this, until #31 has been merged (just to avoid unnecessary conflict resolution on the latter).

### CODE REVIEW

**Comment by dbrgn** [comment]
Regarding #31, it should be easy to resolve the conflicts this way:

- Check out the branch
- Copy over `.prettierrc.yml`
- Reformat the modified files with `npx prettier -w <path-to-file>`
- Amend the commit

Afterwards, you should be able to rebase without conflicts.

Regarding the other request with the debug protocol: Thanks, I wasn't aware of the file's origin. It should be easy to revert just that file.

I think resolving the conflicts and reverting the formatting of `src/debugProtocol.json` would be easier than reverting the entire formatting change and re-applying it later. But if you'd prefer that, that would work as well.

**Comment by noppej** [comment]
No worries. Thank you for being understanding about the `revert` on your excellent submission. 

Also, the `src/` is probably not the right location for me to have stored `debugProtocol.json`  - we should consider moving it :)

**Comment by noppej** [comment]
Merging this revert, so that #31 can go through.

bors r+

**Review by noppej — APPROVED** [review]

**Pull request merged**
