### PR TITLE
Initial release fixes as V0.2.1

### PR DESCRIPTION
**Pull request by noppej**
Some fixes to keep it in synch with the probe-rs/debugger PR and also to reduce the package size.

In order for the included `.vsix` to work, it will require the latest updates to [this PR](https://github.com/probe-rs/probe-rs/pull/620#)

### CODE REVIEW

**Comment by Tiwalun** [comment]
Do you think we could use the Github releases to store the binary? Like in [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-10) for example. I would prefer this to storing a binary file in the repository.

The other changes all look good to me.

**Comment by noppej** [comment]
@Tiwalun  ... great idea.  I will make those changes first thing tomorrow and then merge.

> Do you think we could use the Github releases to store the binary? Like in [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-10) for example. I would prefer this to storing a binary file in the repository.
> 
> The other changes all look good to me.

**Comment by noppej** [comment]
@Tiwalun ... I've made the final changes. Once this branch is in master, I will create a 'release' and publish the updated `.vsix` file. 

> Do you think we could use the Github releases to store the binary? Like in [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-10) for example. I would prefer this to storing a binary file in the repository.
> 
> The other changes all look good to me.

**Review by Tiwalun — APPROVED** [review]
Looks good!

**Pull request merged**
