### PR TITLE
publish also to openvsx marketplace

### LINKED ISSUE #68: Add extension to Open VSX Registry
Love your work, and so it would be nice to have this extension available on [Open VSX Registry](https://open-vsx.org/) so that people could access it easily through editors like VSCodium.

### PR DESCRIPTION
**Pull request by Murmele**
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

1) You need to create an account at https://open-vsx.org
2) Create a token and add it to Github
3)  Claim the ownership https://github.com/eclipse/openvsx/wiki/Namespace-Access
https://github.com/EclipseFdn/open-vsx.org/issues/new?assignees=&labels=namespace&projects=&template=claim-namespace-ownership.md&title=Claiming+namespace+%5Bname%5D

### CODE REVIEW

**Comment by noppej** [comment]
@Murmele Thank you for this. I will action it tomorrow and get back to you if I run into any challenges.

**Comment by noppej** [comment]
All steps are completed, and waiting for https://github.com/EclipseFdn/open-vsx.org/issues/2692 to claim the `probe-rs` namespace in the Open VSX Regsitery.

**Comment by Murmele** [comment]
@noppej thanks you! Hopefully publishing is working fine then. For me it did not work, but I didn't understand the reason for.

**Review by noppej — APPROVED** [review]
I believe all the setup work to publish to Open VSX is now complete.

I will create a new PR that will trigger the workflow to publish as part of the Github action.

**Pull request merged**
