### PR TITLE
Start using prettier

### PR DESCRIPTION
**Pull request by dbrgn**
Automatic code formatting with [prettier](https://prettier.io/) gives us consistent code style without the need for any stylistic discussions.

When using the recommended VSCode extension, code is automatically formatted on save.

Adherence to the prettier code style is checked in CI.

First part of #20.

### CODE REVIEW

**Comment by Yatekii** [comment]
Thank you for using 4 spaces :) And the PR ofc =D

**Comment by dbrgn** [comment]
Ok, after an initial mis-configuration, this should now work (including autoformatting on save).

The configuration is totally open for discussion, I based this on another project.

**Comment by dbrgn** [comment]
Ugh, it seems that prettier has some issues on windows? 🙄 I'm guessing line endings.

**Comment by dbrgn** [comment]
There we go.

**Review by Yatekii — APPROVED** [review]
Looking splendid, thank you very much!

**Comment by noppej** [comment]
@Yatekii and @dbrgn 
I know this might be too late, since this has been merged, but I have two challenges with this:
- We should not reformat `src/debugProtocol.json` ... this file is downloaded from the DAP spec in one of the npm scripts.
- I would have preferred if we could have delayed merging this until after @Yatekii has reviewed and merged #31 ... the premature merging of this has caused some extensive conflicts in #31.

**Comment by noppej** [comment]
@dbrgn We've merged #31. It would be awesome if you are able to re-submit these changes :)

PS. I've moved the offending debugProtocol.json from `src` folder to `dap` folder.

**Pull request merged**
